### ISSUE TITLE
✨ Support for legacy Camera1 devices

### ISSUE THREAD

**Issue by dhirajanand014** [margelo/react-native-vision-camera#127]
## Type

* [ ] I'm cannot build my project with VisionCamera
* [ ] I'm experiencing a full app crash
* [x] A feature is not working correctly
* [ ] Other: __________________

## What
Hi Team,

We are using you library to capture images. When using getAvailableCameraDevices() function from Camera, it returns the length 0 or if we use the 'useCameraDevices' hook, the value returned in undefined, Referring the same code as mentioned from the Sample in the API docs. 

* Platform(s):
  * [ ] iOS
  * [x] Android
* react-native version: 0.64
* react-native-vision-camera version: latest
* react-native-reanimated version: 2.0.1

**Comment by mrousavy** [comment]
Why did you not fill out the template? Share your versions. Which Xiaomi Mi is it? There are multiple versions afaik.
I believe that device does not return any Camera2 compatible devices, it's legacy

**Comment by dhirajanand014** [comment]
Updated the issue with template. Xiomi MI Note 6 Pro is where this issue is occuring and use legacy Camera1 API. What should we do for this?

**Comment by mrousavy** [comment]
VisionCamera requires Camera2 compatible devices, because a lot of features we have in this library are not compatible with Camera1.

To also add support for Camera1 devices I would have to implement https://github.com/cuvent/react-native-vision-camera/issues/78 first, since Camera1 devices will not support Preview + Photo Capture + Video Capture + Frame Processing. I understand that there are still many phones out there using Camera1, but after all it is a _deprecated_ API and I have a few features that have higher priority than supporting legacy devices (such as the Frame Processors PR).

On second thought, the Xiaomi MI Note 6 Pro was released 2018, that should be using Camera2 by now, no?

Try opening your project in Android Studio, then hit Command + Shift + O (two times) to open the `CameraViewModule.kt` file. Put a breakpoint in that line: 

https://github.com/cuvent/react-native-vision-camera/blob/5e2e9b6912e820708f3888c32d6375e3dcc91273/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt#L127

and try stepping through the code to find out what devices are actually available, and why they don't get returned in that function.

**Comment by dhirajanand014** [comment]
When i debug it to the mentioned step with adding breakpoint, The cameraId returned in 0 - which is legacy. How should we proceed further? Should i remove all and start using `react-native-camera`?

**Comment by mrousavy** [comment]
> The cameraId returned in 0

is there only a single camera ID? what if you press "continue", does it not hit the breakpoint again with the next camera?

> which is legacy

how did you determine that?

**Comment by mrousavy** [comment]
Does this get printed in your Logcat console? (in Android Studio, hit command + 6):

https://github.com/cuvent/react-native-vision-camera/blob/5e2e9b6912e820708f3888c32d6375e3dcc91273/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt#L136-L140

**Comment by dhirajanand014** [comment]
Yes this gets printed and the debugger gets a second hit with value 1. However, the above statements is executed and printed.

First debug hit - 
![First debug hit](https://user-images.githubusercontent.com/29733508/116033977-10a1dc80-a680-11eb-935a-0e47ae0c7c42.png)

Second debug hit - 
![Second debug hit](https://user-images.githubusercontent.com/29733508/116034023-257e7000-a680-11eb-97df-2c4e56326bdc.png)

**Comment by mrousavy** [comment]
So for both camera devices (0 and 1) the above line (`"Skipping Camera #(id) because ...."`) will be printed? Could you put a breakpoint here:
https://github.com/cuvent/react-native-vision-camera/blob/5e2e9b6912e820708f3888c32d6375e3dcc91273/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt#L135

and hover over the `hardwareLevel` variable - tell me what value it has (do this for both cameras). Surely they can't be both LEGACY, can they? 🤔 

Then put a breakpoint here: https://github.com/cuvent/react-native-vision-camera/blob/5e2e9b6912e820708f3888c32d6375e3dcc91273/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt#L144

and tell me if that breakpoint is getting hit at all.

**Comment by dhirajanand014** [comment]
Hi,

Sorry for the delay in reply. I checked with what you mentioned to check. 

Yes, for both the cameras for my phone - the hardware level value is got as 2. - 

First snapshot for first breakpoint - 

![1st breakpoint](https://user-images.githubusercontent.com/29733508/117581710-ea6a4b00-b11b-11eb-8a54-a1b4fc9b85c2.png)

Second snapshot for second breakpoint  - 

![2nd breakpoint](https://user-images.githubusercontent.com/29733508/117581947-4f727080-b11d-11eb-8add-ead0f5fcc73b.png)
- 

The line of log gets executed and printed. Not getting any clue how to resolve this.

**Comment by kabus202** [comment]
@dhirajanand014  can you try this on device
go to setting >> additional setting >> developer options >> disable "Turn on MIUI optimization"

**Comment by mrousavy** [comment]
I see, thanks for the detailled infos.

The problem here is that LEGACY devices do not support as many use-cases as normal Camera devices (and iPhones), which is the standard I was going for with VisionCamera.

So for a LEGACY device, you cannot add the "video-capture", "photo-capture", and "preview" use-case at the same time, meaning you could only add "photo-capture" and "preview", or "video-capture" and "preview".

See this table in the link I'm logging in your console:

![Screenshot 2021-05-10 at 09 52 23](https://user-images.githubusercontent.com/15199031/117624659-6e045600-b175-11eb-8e32-b19d23a28dbd.png)

With LIMITED, this already looks a bit better:

![Screenshot 2021-05-10 at 09 52 48](https://user-images.githubusercontent.com/15199031/117624706-7c527200-b175-11eb-8809-fd0d9b07cc4f.png)

but those devices still aren't as good as iPhones, since iPhones can attach "photo-capture" + "video-capture" + "preview" without problems, all in MAXIMUM resolution (except preview obviously). Either way, since LIMITED devices support all three types of capturing at the same time, this is enough for VisionCamera.

And lastly, FULL devices:

![Screenshot 2021-05-10 at 09 53 58](https://user-images.githubusercontent.com/15199031/117624829-a60b9900-b175-11eb-8fbc-b1d03f5fb411.png)

Since VisionCamera allows you to record videos and capture photos in the same camera session without any quirks, I can't think of a nice way to add support for LEGACY devices. What happens if the user tries to use a LEGACY device and tries to start recording? What happens if he wants to record, but takes a picture instead? How will he be able to control whether he wants to add the "video-capture" or the "photo-capture" use-case - remember that he cannot add both?

These are all things that will result in a very ugly API, especially if this is only a legacy-support feature and will not be needed at all anymore in the near future (LEGACY devices are not being produced anymore I think?).

Does anyone know how many Android devices are still on LEGACY level?

### Edit

I just noticed that LEGACY devices support up to three use-case combinations, so "preview", "photo-capture" and "video-capture". With Frame Processors, we can run the frame processing in the video-capture queue as well. This means technically it would be possible to use LEGACY devices with VisionCamera, it just has "preview" quality for video recordings.

@dhirajanand014 remember the breakpoint at the `if` which checks if it is a legacy device? Try removing the entire `if` block and see if it just _works_.

**Comment by dhirajanand014** [comment]
The issue to get the camera working itselfs stops us at the code point where we call the getAvailableCameraDevices method. Here both the cameras are returning value 0 right? How does the camera view work even without them?

**Comment by mrousavy** [comment]
Sorry I don't understand the question, does it still return 0 devices even with my patch/PR?

**Comment by dhirajanand014** [comment]
Tried with the steps mentioned and it dont work. Tried building the app and now shows only white screen. Nothing happens.

**Comment by mrousavy** [comment]
A white screen? Are there any errors shown? Are there any logs in the metro bundler? Are there any logs in Android Studio Logcat? Did the breakpoint get hit?

**Comment by dhirajanand014** [comment]
I thing you can merge.

**Comment by mrousavy** [comment]
What does that mean? Did you test it or not?

**Comment by yfunk** [comment]
> Does anyone know how many Android devices are still on LEGACY level?

I was also interested in this, so I did a bit of research. According to data from http://camera2probe.com ([raw](https://camera2probe.com/device/)) for 3630 unique devices starting at API 23 the split between supported hardware levels (for select minimum API versions) looks like this:

-  **Devices API 23 or newer:** All versions with reliable data. Market share: 84.90% (Google), 93.20% (AppBrain).
-  **Devices API 25 or newer:** Market share: 66.20% (Google), ~83.60% (AppBrain).
-  **Devices API 27 or newer:** Officially supported Android versions ([Wikipedia](https://en.wikipedia.org/wiki/Android_version_history#Overview)). Market share: 53.50% (Google), ~72% (AppBrain).
-  **Devices API 29 or newer:** "New" Android versions. Market share: 8.20% (Google), 45.70% (AppBrain).

|           | API 23+ | API 25+ | API 27+ | API 29+ |
|-----------|---------|---------|---------|---------|
| `LEVEL_3` | 22.59%  | 29.57%  | 35.05%  | 47.20%  |
| `FULL`    | 19.15%  | 22.44%  | 23.96%  | 26.24%  |
| `LIMITED` | 17.36%  | 19.66%  | 20.68%  | 20.75%  |
| `LEGACY`  | 40.91%  | 28.33%  | 20.31%  | 5.81%   |

Since React Native and this library currently support Android back to API 21, where almost half the devices have hardware level `LEGACY`, a feature like described in #78 would definitely be nice to have in the future.

**Comment by mrousavy** [comment]
Those numbers are way higher than I expected. Thanks for the insight @yfunk.

It definitely makes sense to support LEGACY devices, whichever solution it is going to be. I want to try to not change a thing for the library/API to support LEGACY devices, since LEGACY devices do support 3 use-cases, even if video recording will be in PREVIEW sized frames:

![Screenshot 2021-05-19 at 09 42 10](https://user-images.githubusercontent.com/15199031/118774778-7d2a8880-b886-11eb-9f73-16c3168bcb63.png)

> (at least that's how I interpreted [this table](https://developer.android.com/reference/android/hardware/camera2/CameraDevice#regular-capture))

Also, Snapchat works on LEGACY devices right? Snapchat also has three use-cases; PREVIEW, photo-capture and video-capture. They even have a fourth use-case, in-app-processing for those dog-mask filters, but I think that can be chained to the PREVIEW use-case.

**Comment by mrousavy** [comment]
Also, are those market shares realistic values? How many of those phones actually do have e.g. snapchat or other apps installed? What if they're all just drug dealer phones, airport tablets, old grandma phones, etc? @yfunk

**Comment by mrousavy** [comment]
I investigated a bit, taking a look as to how it would be possible with Camera2. We have two approaches:

### Prioritize photo-capture

* Use normal PREVIEW buffer for the preview use-case
* Use PREVIEW sized buffer/frames for video-capture, so video recordings are in poor quality (PREVIEW size is very small on those LEGACY phones)
* Use normal MAXIMUM buffers for photo-capture

### Prioritize video-capture

* Use normal PREVIEW buffer for the preview use-case
* Use MAXIMUM or RECORD buffer/frames for the video-capture to achieve good quality video recordings
* Use PREVIEW buffers for photo-capture by simply screenshotting the PreviewView (same as `takeSnapshot` currently) - this does not support flash and results in poor quality still-images.

I have created a ticket at the google issue tracker asking for advice on this, but I think this is going to be a bad situation either way. Again, LEGACY devices aren't going to be around for long, new devices are being built and the percentages go down. Also, not sure how many people with LEGACY devices download modern apps (since VisionCamera is built for the Cuvent mobile app).

#78 would probably be the best solution to this, I'll try to find a clean API for that.

**Comment by yfunk** [comment]
> Also, are those market shares realistic values? How many of those phones actually do have e.g. snapchat or other apps installed? What if they're all just drug dealer phones, airport tablets, old grandma phones, etc?


The data I used for this is from the Android Developer [Distribution dashboard](https://developer.android.com/about/dashboards), which represents all active Android devices during a 7-day period ending on January 8, 2021. This is what Google provides as a guideline for choosing the `minSdkVersion`, but I agree that this doesn't necessarily reflect actual users who would download modern apps.

I found [data from AppBrain SDK](https://www.appbrain.com/stats/top-android-sdk-versions) (app monetization), which may be better suited for reflecting potential app users and suggests a significantly higher market share of newer devices. I added it in the comment above.

Still, out of all officially supported Android devices one in five are hardware level `LEGACY`, so I don't think this changes the need to eventually support them.

**Comment by mrousavy** [comment]
I've implemented this in #168. Try upgrading to [**2.2.0**](https://github.com/cuvent/react-native-vision-camera/releases/tag/v2.2.0) and make sure to check out [the docs for the `supportsPhotoAndVideoCapture` prop](https://cuvent.github.io/react-native-vision-camera/docs/guides/devices#the-supportsphotoandvideocapture-prop) - let me know if it works for you!

**Comment by K-Leon** [comment]
I just tested it - it looks like this issue isn't solved completely. 

react-native-camera for example falls back to Camera1 - which works - Camera2 ist just producing a black image. I even noticed the usage of these "crazy" hardware in newer devices. 

Is there any easy method to solve this? (Maybe read the images from Camera1 if necessary)
